### ISSUE TITLE
Oddlot

### ISSUE THREAD

**Issue by ihsanyalcinkaya** [hlrs-vis/covise#44]
Hi,

I built COVISE project and I would like to run Oddlot. However, I couldn't manage to run oddlot bash script under the bin directory. How can I run Oddlot?

**Comment by aumuell** [comment]
Most likely, oddlot was not built: our CMakeLists.txt do not enforce that you have all of oddlot's prerequisites, as for many people this is not a required utility.

**Comment by RaviBeagle** [comment]
How can I ensure that I build ODDLOT ? I would like to build only ODDLOT. Is that possible ?

**Comment by uwewoessner** [comment]
Hi RaviBeagle,
ODDLOT depends on a couple of external libraries, you can look at the CMakeLists.txt to find out which they are:
covise_find_package(PROJ4)
using(XercesC)
using(TIFF)
using(JPEG)
using(PROJ4)
USING(BOOST)
using(OpenScenario)
USING(OpenCRG)
using(EIGEN)
and not to forget Qt5.

If it does not find covise, it should compile without the possibility to connect to OpenCOVER, then it should not depend on the covise net, util and config libraries but I never really tested this because we always compile it together with covise.

The easiest way to get ODDLOT is to install the latest COVISE. The installer comes with ODDLOT.
https://fs.hlrs.de/projects/covise/support/download/
If you want to compile it on Windows, I can give you an archive with all the dependencies you require.
If you compile it on Linux, You should be able to install most of the dependencies through your package manager except for OpenCRG. I guess you have to compile that yourself.

**Comment by RaviBeagle** [comment]
Hi uwewoessner,

That's great info!  Should have checked for a reply earlier...
I gave up trying to build on Windows . Now building on Linux - so not much problems for dependencies and should almost be through. Thanks for that offer, will contact when i need the archive. For now I try the installer on Win to check out the features..

**Comment by HolyBugger** [comment]
How can i compile openscenario and openCRG on Linux, where i think they are not some kind of libraries?
Best wishes!

**Comment by RaviBeagle** [comment]
OpenCRG library is not a standard linux package. It has to be downloaded and built I guess:
http://www.opencrg.org/download.html

OpenSCENARIO is i believe is already a component of Covise. Its found here:

covise\src\OpenCOVER\DrivingSim\OpenScenario

**Comment by hbanzhaf** [comment]
Please find detailed instructions on how to build OddLOT [here](https://github.com/hbanzhaf/docker_covise).
