### ISSUE TITLE
OSG Header issue

### ISSUE THREAD

**Issue by RaviBeagle** [hlrs-vis/covise#55]
Hi,

I am trying to build COVISE on Linux Mint 19.1, 
I get this build error:

[ 50%] Building CXX object src/OpenCOVER/plugins/general/Vrml97/CMakeFiles/Vrml97Cover.dir/coMLB.cpp.o
In file included from /home/ravishankar/Downloads/covise/src/OpenCOVER/plugins/general/Vrml97/VrmlNodePhotometricLight.cpp:44:0:
/home/ravishankar/Downloads/covise/src/OpenCOVER/plugins/general/Vrml97/VrmlNodePhotometricLight.h:40:10: fatal error: osg/ComputeDispatch: No such file or directory
 #include <osg/ComputeDispatch>
          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
src/OpenCOVER/plugins/general/Vrml97/CMakeFiles/Vrml97Cover.dir/build.make:422: recipe for target 'src/OpenCOVER/plugins/general/Vrml97/CMakeFiles/Vrml97Cover.dir/VrmlNodePhotometricLight.cpp.o' failed

Strangely that OSG header is not present.

I have the correct version of OSG installed also:

#define OPENSCENEGRAPH_MAJOR_VERSION    3
#define OPENSCENEGRAPH_MINOR_VERSION    4
#define OPENSCENEGRAPH_PATCH_VERSION    1

**Comment by RaviBeagle** [comment]
I installed v3.6 of OSG and got the build to complete successfully. But I get this error on installation:

CMake Error at src/3rdparty/visionaray/src/conv/cmake_install.cmake:41 (file):
  file INSTALL cannot find
  "/home/ravishankar/Downloads/covise/linux64opt/build.covise/src/3rdparty/visionaray/src/conv/conv".
Call Stack (most recent call first):
  src/3rdparty/visionaray/src/cmake_install.cmake:43 (include)
  src/3rdparty/visionaray/cmake_install.cmake:42 (include)
  src/3rdparty/cmake_install.cmake:42 (include)
  src/cmake_install.cmake:42 (include)
  cmake_install.cmake:308 (include)


Makefile:85: recipe for target 'install' failed
make: *** [install] Error 1

Though :

No installation is required: you can use COVISE directly from the build tree.

But I didnt find any binary files.

**Comment by uwewoessner** [comment]
You have to add covise/bin to your path. It contains scripts which set environment variables such as LD_LIBRARAY_PATH and runs the actual executables which are in covise/$ARCHSUFFIX/binUweVon meinem Samsung Galaxy Smartphone gesendet.
-------- Ursprüngliche Nachricht --------Von: RaviBeagle <notifications@github.com> Datum: 06.06.19  16:15  (GMT+01:00) An: hlrs-vis/covise <covise@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Betreff: Re: [hlrs-vis/covise] OSG Header issue (#55) I installed v3.6 of OSG and got the build to complete successfully. But I get this error on installation:
CMake Error at src/3rdparty/visionaray/src/conv/cmake_install.cmake:41 (file):
file INSTALL cannot find
"/home/ravishankar/Downloads/covise/linux64opt/build.covise/src/3rdparty/visionaray/src/conv/conv".
Call Stack (most recent call first):
src/3rdparty/visionaray/src/cmake_install.cmake:43 (include)
src/3rdparty/visionaray/cmake_install.cmake:42 (include)
src/3rdparty/cmake_install.cmake:42 (include)
src/cmake_install.cmake:42 (include)
cmake_install.cmake:308 (include)
Makefile:85: recipe for target 'install' failed
make: *** [install] Error 1
Though :
No installation is required: you can use COVISE directly from the build tree.
But I didnt find any binary files.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/hlrs-vis/covise/issues/55?email_source=notifications\u0026email_token=AAXWTZINRIHVIVBISX3BB4TPZELWXA5CNFSM4HSZBNI2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODXC7JXA#issuecomment-499512540",
"url": "https://github.com/hlrs-vis/covise/issues/55?email_source=notifications\u0026email_token=AAXWTZINRIHVIVBISX3BB4TPZELWXA5CNFSM4HSZBNI2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODXC7JXA#issuecomment-499512540",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by aumuell** [comment]
problem already solved

**Comment by RaviBeagle** [comment]
Thanks. I will now checkout COVISE on Linux sometime. Windows is bit hard..
