### ISSUE TITLE
Error while installing ODDLOT using the docker build

### ISSUE THREAD

**Issue by kanakab** [hlrs-vis/covise#65]
I tried to install the ODDLOT on my Ubuntu 18.04 using the Docker image here: https://github.com/hbanzhaf/docker_covise
I am getting the following error. Please help me to fix this error.

-- The imported target "gdcmpap3" references the file
   "/usr/bin/gdcmpap3"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   "/usr/lib/x86_64-linux-gnu/gdcm-2.8/GDCMTargets.cmake"
but not all the files it references.

-- The imported target "gdcmpdf" references the file
   "/usr/bin/gdcmpdf"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   "/usr/lib/x86_64-linux-gnu/gdcm-2.8/GDCMTargets.cmake"
but not all the files it references.

-- Could NOT find CGNS (missing: CGNS_LIBRARY CGNS_INCLUDE_DIR) 
-- Could NOT find CGNS (missing: CGNS_LIBRARY CGNS_INCLUDE_DIR) 
-- Could NOT find Cg (missing: CG_LIBRARY CG_GL_LIBRARY CG_INCLUDE_DIR CG_COMPILER) 
-- Could NOT find ARTOOLKIT (missing: ARTOOLKIT_AR_LIBRARY ARTOOLKIT_ARGSUB_LIBRARY ARTOOLKIT_ARVIDEO_LIBRARY ARTOOLKIT_INCLUDE_DIR ARTOOLKIT_DC1394_LIBRARY ARTOOLKIT_RAW1394_LIBRARY ARTOOLKIT_DV_LIBRARY) 
-- Could NOT find JPEGTURBO (missing: TURBOJPEG_LIBRARY JPEGTURBO_INCLUDE_DIR) 
-- Could NOT find VRPN (missing: VRPN_VRPN_LIBRARY VRPN_QUAT_LIBRARY VRPN_INCLUDE_DIR) 
CUDA_TOOLKIT_ROOT_DIR not found or specified
-- Could NOT find CUDA (missing: CUDA_TOOLKIT_ROOT_DIR CUDA_NVCC_EXECUTABLE CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY) 
-- Could NOT find osgDB (missing: OSGDB_LIBRARY OSGDB_INCLUDE_DIR) 
-- Could NOT find osgUtil (missing: OSGUTIL_LIBRARY OSGUTIL_INCLUDE_DIR) 
-- Could NOT find osgViewer (missing: OSGVIEWER_LIBRARY OSGVIEWER_INCLUDE_DIR) 
-- Could NOT find osgParticle (missing: OSGPARTICLE_LIBRARY OSGPARTICLE_INCLUDE_DIR) 
-- Could NOT find osgText (missing: OSGTEXT_LIBRARY OSGTEXT_INCLUDE_DIR) 
-- Could NOT find osgSim (missing: OSGSIM_LIBRARY OSGSIM_INCLUDE_DIR) 
-- Could NOT find osgGA (missing: OSGGA_LIBRARY OSGGA_INCLUDE_DIR) 
-- Could NOT find osgFX (missing: OSGFX_LIBRARY OSGFX_INCLUDE_DIR) 
-- Could NOT find osgTerrain (missing: OSGTERRAIN_LIBRARY OSGTERRAIN_INCLUDE_DIR) 
-- Could NOT find osgShadow (missing: OSGSHADOW_LIBRARY OSGSHADOW_INCLUDE_DIR) 
-- Could NOT find osg (missing: OSG_LIBRARY OSG_INCLUDE_DIR) 
-- Could NOT find OpenThreads (missing: OPENTHREADS_LIBRARY OPENTHREADS_INCLUDE_DIR) 
CMake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find OpenSceneGraph (missing: OPENSCENEGRAPH_LIBRARIES
  OPENSCENEGRAPH_INCLUDE_DIR OSGDB_FOUND OSGUTIL_FOUND OSGVIEWER_FOUND
  OSGPARTICLE_FOUND OSGTEXT_FOUND OSGSIM_FOUND OSGGA_FOUND OSGFX_FOUND
  OSGTERRAIN_FOUND OSGSHADOW_FOUND OSG_FOUND OPENTHREADS_FOUND) (Required is
  at least version "3.2.0")
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.10/Modules/FindOpenSceneGraph.cmake:223 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  cmake/CoviseHelperMacros.cmake:938 (FIND_PACKAGE)
  src/OpenCOVER/CMakeLists.txt:122 (covise_find_package)

-- Configuring incomplete, errors occurred!
See also "/home/sl-ubuntu/Downloads/covise/bionicopt/build.covise/CMakeFiles/CMakeOutput.log".
See also "/home/sl-ubuntu/Downloads/covise/bionicopt/build.covise/CMakeFiles/CMakeError.log".

**Comment by uwewoessner** [comment]
Sorry, I can't help here. The issue is that OpenSceneGraph is missing. as far as I can tell the docker build script should have installed OpenSceneGraph but that apparently failed. Please check the installation of OpenSceneGraph or ask in the docker build group.

**Comment by aumuell** [comment]
If you could not solve the problem, please bring up the issue in the [repo of the docker container](https://github.com/hbanzhaf/docker_covise): this is not something that we can fix by editing COVISE source code or build instructions.

**Comment by aumuell** [comment]
I just tried the docker build, and it worked for me exactly as documented. One should note though that the docker image will not contain COVISE, just its dependencies - including OpenSceneGraph and OpenCRG. After building the container, it has to be launched via `docker-compose`, and then you have to execute the listed commands for downloading and building COVISE from source - and this has to be done inside the container. It will map your host's Download directory into the container, and you are instructed to build COVISE in that directory, so that the build persists between launches of the container.

You mention that your host OS is Ubuntu 18.04, the same OS that has been used for this container. Did you, by accident, try to execute the commands for building COVISE directly on your host? This would explain why it cannot find OpenSceneGraph.

Given that your host OS matches the container OS, it should be possible to install COVISE dependencies on your host by replicating the commands from `Dockerfile` . Then it should be possible to execute the COVISE installation as described directly on your host, without a need for docker.
