### ISSUE TITLE
How to build a new clothoid (spiral) road with OddLOT

### ISSUE THREAD

**Issue by johschmitz** [hlrs-vis/covise#75]
I could not find a way to buid a new clothoid road with OddLOT. If it is possible could you please tell me how?

**Comment by uwewoessner** [comment]
Currently you have to start a road with a straight line segment, only then you can add a transition consisting of a clothoid, arc and a second clothoid. If you want to keep only one clothoid, you have to remove the second clothoid and the arc.
Go to Track editor, create a new Road, drag a line, then switch to Append, go to ParameterSettings on the right(we have to move this on top, so that you don't have to scroll for these settings) There you can change the primitive type to ARC/Spiral. Now you can add clothoids to your road.

**Comment by aumuell** [comment]
seems to have been answered
